spec:
  inputs:
    go_image:
      default: "golang:1.25"
      description: "Image used for the test job."
---
include:
  - local: /lock.yml

stages:
  - lint
  - test

.go-vars: &go-vars
  GOTOOLCHAIN: local
  GOFLAGS: -buildvcs=false
  GOMODCACHE: $CI_PROJECT_DIR/.cache/go-mod
  GOCACHE: $CI_PROJECT_DIR/.cache/go-build
  GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache/golangci

.go-cache: &go-cache
  key:
    files:
      - go.sum
  paths:
    - .cache/

lint:
  stage: lint
  image: $STACK_GO_TOOLS_IMAGE
  tags:
    - self-hosted
  variables:
    <<: *go-vars
  cache:
    - *go-cache
  script:
    - eiseron go lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  image: $[[ inputs.go_image ]]
  tags:
    - self-hosted
  variables:
    <<: *go-vars
  cache:
    - *go-cache
  script:
    - go test ./... -race
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
